import Head from "next/head";
import HeroSection from "@/components/HeroSection";
import Statistics from "@/components/Statistics";
import About from "@/components/About";
import Clients from "@/components/Clients";
import Services from "@/components/Services";
import Portfolio from "@/components/Portfolio";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Real Estate</title>
      </Head>
      <main className="flex flex-col">
        <section>

        <HeroSection />
        </section>
        <section className="mb-12">
          <Statistics></Statistics>
        </section>
        <section className="mb-12">
          <About></About>
        </section>

        <section className="mb-12">
          <Services></Services>
        </section>

        <section className="mb-12">
          <Portfolio />
        </section>

        <section className="my-24">
          <Clients></Clients>
        </section>
      </main>
    </>
  );
}
