import Head from "next/head";
import HeroSection from "@/components/HeroSection";
import Statistics from "@/components/Statistics";
import About from "@/components/About";
import Clients from "@/components/Clients";
import Services from "@/components/Services";
import Portfolio from "@/components/Portfolio";
import Contact from "@/components/Contact";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.svg" />
        <title>Real Estate</title>
      </Head>
      <main className="flex flex-col">
        <section id="main">
          <HeroSection />
        </section>
        <section className="mb-12">
          <Statistics></Statistics>
        </section>
        <section id="about" className="mb-12">
          <About ></About>
        </section>

        <section  id="services" className="mb-12 mt-24">
          <Services></Services>
        </section>

        <section  id="portfolio" className="mb-12">
          <Portfolio />
        </section>

        <section  id="clients" className="my-24">
          <Clients></Clients>
        </section>

        <section id="contact">
          <Contact></Contact>
        </section>
      </main>
    </>
  );
}
