import Head from "next/head";
import HeroSection from "@/components/HeroSection";
import Statistics from "@/components/Statistics";
import About from "@/components/About";
import Clients from "@/components/Clients";
import Services from "@/components/Services";
import Portfolio from "@/components/Portfolio";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col">
        <HeroSection />
        <div id="bout-section">
          <Statistics></Statistics>
          <div className="my-8"></div>
          <About></About>
          <div className="mt-36"></div>
          <Services></Services>
          <div className="my-8"></div>
          <Portfolio />
          <div className="my-8"></div>
          <Clients></Clients>
        </div>
      </main>
    </>
  );
}
